### ISSUE TITLE
functools attribute error was found

### ISSUE THREAD

**Issue by hulihan-start** [roastduck/FreeTensor#498]
After I pull the up-to-date code in my environment, another error was found:

Traceback (most recent call last):
  File "example.py", line 34, in <module>
    import freetensor as ft
  File "/data/not_backed_up/lihhu/FreeTensor_experiments/FreeTensor/python/freetensor/__init__.py", line 1, in <module>
    from . import core
  File "/data/not_backed_up/lihhu/FreeTensor_experiments/FreeTensor/python/freetensor/core/__init__.py", line 14, in <module>
    from .autograd import *
  File "/data/not_backed_up/lihhu/FreeTensor_experiments/FreeTensor/python/freetensor/core/autograd.py", line 17, in <module>
    from .transform import transform, inline
  File "/data/not_backed_up/lihhu/FreeTensor_experiments/FreeTensor/python/freetensor/core/transform.py", line 32, in <module>
    jit_cache: Callable[Callable, Callable] = functools.cache,
AttributeError: module 'functools' has no attribute 'cache'

Is there any suggestion for this error? 

Thank you!

**Comment by roastduck** [comment]
`functools` is a built-in package from Python, and there is indeed a `functools.cache`. Please check your Python installation's integrity.

**Comment by hulihan-start** [comment]
Thanks a lot. My Python version is 3.8.10, but the functools.cache is a new function in Python 3.9.
